name: GitHub Actions Demo
on: [push]
jobs:
  Run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@v3
        with:
          Token: ${{secrets.GITHUB_TOKEN}}
      - name: install python 
        uses: actions/setup-python@v4
      - name: install pytest
        run: pip3 install pytest
      - name: run pytest
        run: | 
          curl -IL www.github.com/users
          pwd
          pytest -vs tests